import Head from "next/head";

import Protokol from "../components/theme/Protokol";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Gold-satu</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        ></link>
        <link rel="icon" href="/favicon.icon" />
      </Head>
      
    <Protokol/>
  
    </div>
  );
}